### ISSUE TITLE
How do the different members of the group communicate

### ISSUE THREAD

**Issue by mgw-sbex** [po5/groupwatch_sync#1]
HI po5, we are interested to try this repo. We noticed it seems to be a similar concept to Syncplay for mpv. With groupwatch, how  does each member of the group communicate their current position to the group?

**Comment by po5** [comment]
Participants sync using an external clock e.g. [time.is](https://time.is/) or an IRC bot announcing when to start.  
The benefit to such a technique is that everyone can use their own preferred media player setup.

I wrote this to automate getting back in sync with the group if you happen to pause.

Noticed your issue at Syncplay/syncplay#299. Syncplay expects everyone to be running syncplay, while this is nothing but a helper for the technique described above.

There certainly are ways to automatically set the start time across all participants, but this would require others to also be using mpv/a compatible plugin for some other player.  
I would consider this out of scope.

Feel free to implement that behavior, I will license the code under whatever is convenient.

**Comment by mgw-sbex** [comment]
Hi po5, thank you for explaining. When we use your repo, how do the participants know if they are in sync with others after they try to catch up?

**Comment by po5** [comment]
If activating the `groupwatch_sync` script binding (default key is k) displays `[groupwatch_sync] synced` in the osd, you are in sync with the group within 0.1 seconds.

**Comment by po5** [comment]
Update on this, you no longer need an external clock and only have to communicate the start time, which each participant sets in their player with Ctrl+Shift+k.
